### PR TITLE
Deprecate Ember.Inflector, Ember.String.singularize() and Ember.String.pluralize()

### PR DESCRIPTION
**Pull request by Turbo87**
Resolves parts of #125

/cc @rwjblue

### CODE REVIEW

**Comment by Turbo87** [comment]
@stefanpenner @fivetanley any comments?

**Comment by fsmanuel** [comment]
👍

**Comment by fsmanuel** [comment]
@Turbo87 We should update the readme [usage](https://github.com/emberjs/ember-inflector#usage).
* Change or remove the first line
* remove
```js
// or if not using Ember CLI/ES6
Ember.Inflector.inflector.pluralize("taco"); // tacos
```

**Comment by Turbo87** [comment]
@fsmanuel good point, will update that too

**Comment by rwjblue** [comment]
We need to update ember-data to avoid the deprecation before landing this.

**Comment by locks** [comment]
Ember Data should be updated, with a backport to release, according to linked PRs. Merge?

**Comment by rwjblue** [comment]
Yes, this is ready to merge and release. I’ll try to do it in the AM...

**Comment by Turbo87** [comment]
@rwjblue reminder, just in case you forgot :)

**Pull request merged**
